# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalogo_pb2 as catalogo__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in catalogo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class servidorCatalogoStub(object):
    """servidorCatalogo.py
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.queryCategoria = channel.unary_unary(
                '/servidorCatalogo/queryCategoria',
                request_serializer=catalogo__pb2.CategoriaRequest.SerializeToString,
                response_deserializer=catalogo__pb2.ListaLivros.FromString,
                _registered_method=True)
        self.queryNumero = channel.unary_unary(
                '/servidorCatalogo/queryNumero',
                request_serializer=catalogo__pb2.numeroItemRequest.SerializeToString,
                response_deserializer=catalogo__pb2.LivroInfo.FromString,
                _registered_method=True)
        self.update = channel.unary_unary(
                '/servidorCatalogo/update',
                request_serializer=catalogo__pb2.UpdateRequest.SerializeToString,
                response_deserializer=catalogo__pb2.UpdateResponse.FromString,
                _registered_method=True)


class servidorCatalogoServicer(object):
    """servidorCatalogo.py
    """

    def queryCategoria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryNumero(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_servidorCatalogoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'queryCategoria': grpc.unary_unary_rpc_method_handler(
                    servicer.queryCategoria,
                    request_deserializer=catalogo__pb2.CategoriaRequest.FromString,
                    response_serializer=catalogo__pb2.ListaLivros.SerializeToString,
            ),
            'queryNumero': grpc.unary_unary_rpc_method_handler(
                    servicer.queryNumero,
                    request_deserializer=catalogo__pb2.numeroItemRequest.FromString,
                    response_serializer=catalogo__pb2.LivroInfo.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=catalogo__pb2.UpdateRequest.FromString,
                    response_serializer=catalogo__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'servidorCatalogo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('servidorCatalogo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class servidorCatalogo(object):
    """servidorCatalogo.py
    """

    @staticmethod
    def queryCategoria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidorCatalogo/queryCategoria',
            catalogo__pb2.CategoriaRequest.SerializeToString,
            catalogo__pb2.ListaLivros.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryNumero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidorCatalogo/queryNumero',
            catalogo__pb2.numeroItemRequest.SerializeToString,
            catalogo__pb2.LivroInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidorCatalogo/update',
            catalogo__pb2.UpdateRequest.SerializeToString,
            catalogo__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class servidorPedidosStub(object):
    """servidorPedidos.py
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Buy = channel.unary_unary(
                '/servidorPedidos/Buy',
                request_serializer=catalogo__pb2.numeroItemRequest.SerializeToString,
                response_deserializer=catalogo__pb2.CompraResponse.FromString,
                _registered_method=True)


class servidorPedidosServicer(object):
    """servidorPedidos.py
    """

    def Buy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_servidorPedidosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Buy': grpc.unary_unary_rpc_method_handler(
                    servicer.Buy,
                    request_deserializer=catalogo__pb2.numeroItemRequest.FromString,
                    response_serializer=catalogo__pb2.CompraResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'servidorPedidos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('servidorPedidos', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class servidorPedidos(object):
    """servidorPedidos.py
    """

    @staticmethod
    def Buy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidorPedidos/Buy',
            catalogo__pb2.numeroItemRequest.SerializeToString,
            catalogo__pb2.CompraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class servidorFrontStub(object):
    """servidorFront.py
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/servidorFront/Search',
                request_serializer=catalogo__pb2.CategoriaRequest.SerializeToString,
                response_deserializer=catalogo__pb2.ListaLivros.FromString,
                _registered_method=True)
        self.Lookup = channel.unary_unary(
                '/servidorFront/Lookup',
                request_serializer=catalogo__pb2.numeroItemRequest.SerializeToString,
                response_deserializer=catalogo__pb2.LivroInfo.FromString,
                _registered_method=True)
        self.Buy = channel.unary_unary(
                '/servidorFront/Buy',
                request_serializer=catalogo__pb2.numeroItemRequest.SerializeToString,
                response_deserializer=catalogo__pb2.CompraResponse.FromString,
                _registered_method=True)


class servidorFrontServicer(object):
    """servidorFront.py
    """

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Buy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_servidorFrontServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=catalogo__pb2.CategoriaRequest.FromString,
                    response_serializer=catalogo__pb2.ListaLivros.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=catalogo__pb2.numeroItemRequest.FromString,
                    response_serializer=catalogo__pb2.LivroInfo.SerializeToString,
            ),
            'Buy': grpc.unary_unary_rpc_method_handler(
                    servicer.Buy,
                    request_deserializer=catalogo__pb2.numeroItemRequest.FromString,
                    response_serializer=catalogo__pb2.CompraResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'servidorFront', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('servidorFront', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class servidorFront(object):
    """servidorFront.py
    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidorFront/Search',
            catalogo__pb2.CategoriaRequest.SerializeToString,
            catalogo__pb2.ListaLivros.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidorFront/Lookup',
            catalogo__pb2.numeroItemRequest.SerializeToString,
            catalogo__pb2.LivroInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Buy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidorFront/Buy',
            catalogo__pb2.numeroItemRequest.SerializeToString,
            catalogo__pb2.CompraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
