# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalogo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'catalogo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61talogo.proto\"%\n\x10\x43\x61tegoriaRequest\x12\x11\n\tcategoria\x18\x01 \x01(\t\"\'\n\x11numeroItemRequest\x12\x12\n\nnumeroItem\x18\x01 \x01(\x05\"0\n\rUpdateRequest\x12\x12\n\nnumeroItem\x18\x01 \x01(\x05\x12\x0b\n\x03qty\x18\x02 \x01(\x05\"c\n\tLivroInfo\x12\x12\n\nnumeroItem\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tcategoria\x18\x03 \x01(\t\x12\x12\n\nquantidade\x18\x04 \x01(\x05\x12\r\n\x05\x65rror\x18\x05 \x01(\t\")\n\x0bListaLivros\x12\x1a\n\x06livros\x18\x01 \x03(\x0b\x32\n.LivroItem\"-\n\tLivroItem\x12\x12\n\nnumeroItem\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\"2\n\x0e\x43ompraResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9f\x01\n\x10servidorCatalogo\x12\x31\n\x0equeryCategoria\x12\x11.CategoriaRequest\x1a\x0c.ListaLivros\x12-\n\x0bqueryNumero\x12\x12.numeroItemRequest\x1a\n.LivroInfo\x12)\n\x06update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse2=\n\x0fservidorPedidos\x12*\n\x03\x42uy\x12\x12.numeroItemRequest\x1a\x0f.CompraResponse2\x90\x01\n\rservidorFront\x12)\n\x06Search\x12\x11.CategoriaRequest\x1a\x0c.ListaLivros\x12(\n\x06Lookup\x12\x12.numeroItemRequest\x1a\n.LivroInfo\x12*\n\x03\x42uy\x12\x12.numeroItemRequest\x1a\x0f.CompraResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalogo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORIAREQUEST']._serialized_start=18
  _globals['_CATEGORIAREQUEST']._serialized_end=55
  _globals['_NUMEROITEMREQUEST']._serialized_start=57
  _globals['_NUMEROITEMREQUEST']._serialized_end=96
  _globals['_UPDATEREQUEST']._serialized_start=98
  _globals['_UPDATEREQUEST']._serialized_end=146
  _globals['_LIVROINFO']._serialized_start=148
  _globals['_LIVROINFO']._serialized_end=247
  _globals['_LISTALIVROS']._serialized_start=249
  _globals['_LISTALIVROS']._serialized_end=290
  _globals['_LIVROITEM']._serialized_start=292
  _globals['_LIVROITEM']._serialized_end=337
  _globals['_COMPRARESPONSE']._serialized_start=339
  _globals['_COMPRARESPONSE']._serialized_end=389
  _globals['_UPDATERESPONSE']._serialized_start=391
  _globals['_UPDATERESPONSE']._serialized_end=424
  _globals['_SERVIDORCATALOGO']._serialized_start=427
  _globals['_SERVIDORCATALOGO']._serialized_end=586
  _globals['_SERVIDORPEDIDOS']._serialized_start=588
  _globals['_SERVIDORPEDIDOS']._serialized_end=649
  _globals['_SERVIDORFRONT']._serialized_start=652
  _globals['_SERVIDORFRONT']._serialized_end=796
# @@protoc_insertion_point(module_scope)
